// AUTO-GENERATED by apply-fixes.mjs
// Sanitizes HTML so CMS/user/markdown content can't inject <script>.
// Requires: npm i isomorphic-dompurify
import DOMPurify from "isomorphic-dompurify";

export function sanitizeHtml(dirty: string): string {
  return DOMPurify.sanitize(dirty ?? "", {
    ALLOWED_TAGS: [
      "p","br","b","strong","i","em","u","s","span","div","a","ul","ol","li",
      "blockquote","code","pre","hr","h1","h2","h3","h4","h5","h6","img",
      "figure","figcaption","table","thead","tbody","tr","th","td",
    ],
    ALLOWED_ATTR: ["href","src","alt","title","class","target","rel","width","height"],
    ALLOW_DATA_ATTR: false,
  });
}
