#!/usr/bin/env node
/**
 * apply-fixes.mjs — ONE command that auto-applies every safe fix for Rose & Co.
 *
 * What it does (all reversible via your git backup):
 *   1. Creates src/lib/sanitize.ts (DOMPurify helper).
 *   2. Wraps every dangerouslySetInnerHTML __html value in sanitizeHtml(...)
 *      — keeps your JSX/tags/classes identical, only sanitizes the value.
 *      Skips JsonLd.tsx (JSON-LD must NOT be sanitized) and already-safe files.
 *   3. Swaps <img>/src ".png" -> ".webp" in code where a .webp exists in /public,
 *      then deletes the now-unused heavy .png originals.
 *   4. Adds rel="noopener noreferrer" to any target="_blank" missing it
 *      (handles arrow-function attributes that broke the old script).
 *
 * SAFE: run `git add -A && git commit -m "backup"` first (you already did).
 * Preview everything with:  node apply-fixes.mjs --dry
 * Apply for real with:      node apply-fixes.mjs
 */
import { readdir, readFile, writeFile, stat, unlink, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, extname, basename, dirname, relative } from "node:path";

const DRY = process.argv.includes("--dry");
const ROOT = process.cwd();
const SRC = join(ROOT, "src");
const PUBLIC = join(ROOT, "public");
const CODE_EXT = new Set([".tsx", ".jsx", ".ts", ".js"]);
const SKIP_DIRS = new Set(["node_modules", ".next", ".git", "dist", "build", "out", ".vercel"]);
// Never rewrite these — they are the sanitizer itself or must stay raw.
const SKIP_SANITIZE = new Set(["sanitize.ts", "sanitize.tsx", "SafeHtml.tsx", "JsonLd.tsx"]);

const log = (...a) => console.log(...a);
let counts = { sanitize: 0, imgSwap: 0, imgDel: 0, noopener: 0, filesTouched: new Set() };

// ---------- gather code files ----------
async function collect(dir, out = []) {
  let entries;
  try { entries = await readdir(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    if (e.isDirectory()) { if (!SKIP_DIRS.has(e.name)) await collect(join(dir, e.name), out); }
    else if (CODE_EXT.has(extname(e.name).toLowerCase())) out.push(join(dir, e.name));
  }
  return out;
}

// ---------- 1 & 2: sanitize helper + codemod ----------
const SANITIZE_TS = `// AUTO-GENERATED by apply-fixes.mjs
// Sanitizes HTML so CMS/user/markdown content can't inject <script>.
// Requires: npm i isomorphic-dompurify
import DOMPurify from "isomorphic-dompurify";

export function sanitizeHtml(dirty: string): string {
  return DOMPurify.sanitize(dirty ?? "", {
    ALLOWED_TAGS: [
      "p","br","b","strong","i","em","u","s","span","div","a","ul","ol","li",
      "blockquote","code","pre","hr","h1","h2","h3","h4","h5","h6","img",
      "figure","figcaption","table","thead","tbody","tr","th","td",
    ],
    ALLOWED_ATTR: ["href","src","alt","title","class","target","rel","width","height"],
    ALLOW_DATA_ATTR: false,
  });
}
`;

async function ensureSanitizeHelper() {
  const dir = join(SRC, "lib");
  const file = join(dir, "sanitize.ts");
  if (existsSync(file)) { log("• sanitize.ts already exists — leaving it"); return; }
  if (!DRY) { await mkdir(dir, { recursive: true }); await writeFile(file, SANITIZE_TS); }
  log(`✎ ${DRY ? "[dry] would create" : "created"} src/lib/sanitize.ts`);
}

// Matches: __html: <expr> } }  (non-greedy up to the closing }} )
const HTML_RE = /__html:\s*([^}]+?)\s*}\s*}/g;

function importPathFor(file) {
  // prefer the @/ alias if the project uses src/, else relative
  return "@/lib/sanitize";
}

async function codemodSanitize(files) {
  for (const f of files) {
    if (SKIP_SANITIZE.has(basename(f))) continue;
    let src = await readFile(f, "utf8");
    if (!src.includes("dangerouslySetInnerHTML")) continue;
    let changed = 0;
    const out = src.replace(HTML_RE, (m, expr) => {
      const e = expr.trim();
      if (/^sanitizeHtml\s*\(/.test(e)) return m;          // already wrapped
      if (/JSON\.stringify/.test(e)) return m;             // JSON-LD payload, skip
      changed++;
      return `__html: sanitizeHtml(${e}) }}`;
    });
    if (changed > 0) {
      let final = out;
      if (!/from\s+["']@\/lib\/sanitize["']/.test(final)) {
        // insert import after the last existing import, else at top
        const imports = [...final.matchAll(/^import .*$/gm)];
        const inject = `import { sanitizeHtml } from "${importPathFor(f)}";\n`;
        if (imports.length) {
          const last = imports[imports.length - 1];
          const at = last.index + last[0].length;
          final = final.slice(0, at) + "\n" + inject.trimEnd() + final.slice(at);
        } else {
          final = inject + final;
        }
      }
      counts.sanitize += changed; counts.filesTouched.add(f);
      log(`✎ ${DRY ? "[dry] " : ""}sanitize x${changed}  ${relative(ROOT, f)}`);
      if (!DRY) await writeFile(f, final);
    }
  }
}

// ---------- 3: image .png -> .webp swap + delete originals ----------
async function listWebpBasenames(dir, set = new Set()) {
  let entries;
  try { entries = await readdir(dir, { withFileTypes: true }); } catch { return set; }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) await listWebpBasenames(p, set);
    else if (extname(e.name).toLowerCase() === ".webp") set.add(basename(e.name, ".webp"));
  }
  return set;
}

async function swapImages(files) {
  const webpNames = await listWebpBasenames(PUBLIC);
  if (webpNames.size === 0) { log("• no .webp files found in /public — run compress-images.mjs first"); return; }
  // 3a. update references in code
  for (const f of files) {
    let src = await readFile(f, "utf8");
    let changed = 0;
    const out = src.replace(/([\w\-./]+)\.png/g, (m, stem) => {
      const base = basename(stem);
      if (webpNames.has(base)) { changed++; return `${stem}.webp`; }
      return m;
    });
    if (changed > 0) {
      counts.imgSwap += changed; counts.filesTouched.add(f);
      log(`✎ ${DRY ? "[dry] " : ""}img .png→.webp x${changed}  ${relative(ROOT, f)}`);
      if (!DRY) await writeFile(f, out);
    }
  }
  // 3b. delete original PNGs that now have a webp twin
  async function delPngs(dir) {
    let entries;
    try { entries = await readdir(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      const p = join(dir, e.name);
      if (e.isDirectory()) { await delPngs(p); continue; }
      if (extname(e.name).toLowerCase() === ".png" && webpNames.has(basename(e.name, ".png"))) {
        counts.imgDel++;
        log(`🗑  ${DRY ? "[dry] would delete " : "deleted "}${relative(ROOT, p)}`);
        if (!DRY) await unlink(p);
      }
    }
  }
  await delPngs(PUBLIC);
}

// ---------- 4: rel=noopener (arrow-safe) ----------
async function fixNoopener(files) {
  const TARGET = /target\s*=\s*["']_blank["']/g;
  for (const f of files) {
    let src = await readFile(f, "utf8");
    let changed = 0;
    let out = src.replace(TARGET, (m, offset) => {
      // look ~200 chars ahead for an existing rel= before the tag likely closes
      const ahead = src.slice(offset, offset + 200);
      if (/\brel\s*=/.test(ahead)) return m;
      changed++;
      return `${m} rel="noopener noreferrer"`;
    });
    if (changed > 0) {
      counts.noopener += changed; counts.filesTouched.add(f);
      log(`✎ ${DRY ? "[dry] " : ""}noopener x${changed}  ${relative(ROOT, f)}`);
      if (!DRY) await writeFile(f, out);
    }
  }
}

// ---------- run ----------
log(`\n🔧 Rose & Co auto-fix ${DRY ? "(DRY RUN — nothing written)" : ""}\n`);
const files = await collect(SRC);
log(`Scanning ${files.length} code files under src/ ...\n`);
await ensureSanitizeHelper();
await codemodSanitize(files);
await swapImages(files);
await fixNoopener(files);

log(`\n───────── summary ─────────`);
log(`  sanitize wraps : ${counts.sanitize}`);
log(`  images swapped : ${counts.imgSwap}`);
log(`  pngs deleted   : ${counts.imgDel}`);
log(`  noopener added : ${counts.noopener}`);
log(`  files changed  : ${counts.filesTouched.size}`);
log(DRY ? `\nDry run only. Re-run without --dry to apply.\n`
       : `\n✅ Applied. Now run:  npm run dev   (test)   then re-audit.\n`);
